### PR TITLE
Translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by giuliatondin**
I wanted to do this translation of this repository to Brazilian Portuguese, because I think it will help brazilians anyway.

### CODE REVIEW

**Comment by ZuzooVn** [comment]
Please keep your translation updated as the English version changes over time.
Are you okay with doing that?

**Comment by oude3c** [comment]
GOOD

**Comment by giuliatondin** [comment]
@ZuzooVn yeah, of course! I'll change right now, sorry. Besides, great work!

**Comment by ZuzooVn** [comment]
LGTM

**Comment by ZuzooVn** [comment]
Can you update Brazilian Portuguese version?

Thanks

**Comment by STEW1327** [comment]
can you send it to my now tv box

**Comment by STEW1327** [comment]
192.168.0.11

**Pull request merged**
