### PR TITLE
grammar errors

### PR DESCRIPTION
**Pull request by jesusgalvan**

### CODE REVIEW

**Comment by ZuzooVn** [comment]
Thanks

**Comment by xyclos** [comment]
Why was this merged?  Is it meant to be posed as a question like `Don't feel you are smart enough?` If not then the original was correct.  If so, then the question mark needs to be added otherwise this doesn't really make sense.

**Comment by ZuzooVn** [comment]
I rechecked and reverted to the original version.
Thanks

**Comment by jesusgalvan** [comment]
@xyclos 
Original text was [Don't feel you aren't smart enough] which does not make sense when expanded 
[Don't feel you are not smart enough] Double negative.

Should either be
[Feel you aren't smart enough?]
or
[Don't feel you are smart enough?]

**Comment by xyclos** [comment]
@jesusgalvan There isn't anything wrong with "Do not feel you are not smart enough". The two negatives in the sentence support two separate prepositional phrases. "Do not" negates "feel" (verb - first preposition) and "Are not" negates "smart" (adjective - second preposition). This is not a double negative.  A double negative would be something like "Don't not feel" or "Aren't never smart". There may be a better way to phrase it, but the original did not contain a grammatical error and the change made in the PR changed the meaning of the sentence entirely.

**Comment by jesusgalvan** [comment]
@xyclos wrong, but do as you wish 😄

**Comment by ZuzooVn** [comment]
@xyclos @jesusgalvan : What I mean was: "stop thinking you’re stupid , overcoming the fear of not being good enough"

**Pull request merged**
